version: '3.9'
services:
  jdk:
    image: 'eclipse-temurin:17-jdk-alpine'
    container_name: 'jdk'
    volumes:
      - './root:/root'
    entrypoint: sh -c 'trap exit TERM; tail -f /dev/null & wait $!'
  db:
    image: 'postgres:16-alpine'
    container_name: 'db'
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=db'
  adminer:
    image: 'adminer'
    container_name: 'adminer'
    ports:
      - '8080:8080'
